spring.application.name=restcontrol-api

# Configuração de Conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/restcontrol
spring.datasource.username=postgres
spring.datasource.password=adminPostgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Forçar a porta 8081 para não conflitar com sua outra aplicação
server.port=8081